---
title: "rough work"
author: "Sciper 359523"
date: "2023-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r working directory and data, echo=FALSE, include=FALSE}
lapply(c("dplyr","chron","ggplot2","tidyr","questionr","survival","forcats","tidyselect",
         "data.table","table1","lubridate", "ggpubr","viridis","finalfit","survminer",
         "ggpubr", "ggthemes", "gridExtra", "rstatix","stringr",
         "wesanderson","kableExtra", "naniar","boot","scales","ggsci", "stringr",
         "Hmisc","DescTools","swimplot", 'stats', 'EnvStats', 'finalfit'), 
       library, character.only=TRUE)

set.seed(435) #set the seed for reproducible results

#setwd("C:/Users/candi/Desktop/ETUDES/EPFL1A/semestre 2/applied statistics/applied_stat_359523/project_4")
df_usa <- read.table('4_US_elections.txt', header=T)
```


## Data exploration 
```{r data set modif}
df_usa <- df_usa %>% mutate(
  region = as.factor(case_when(
    state == 7~ 'Northeast',
    state == 8~'Northeast',
    state == 19~ 'Northeast',
    state == 20~ 'Northeast',
    state == 21~ 'Northeast',
    state == 29~ 'Northeast',
    state == 30~ 'Northeast',
    state == 32~ 'Northeast',
    state == 38~ 'Northeast',
    state == 39~ 'Northeast',
    state == 45~ 'Northeast', 
    state == 48~ 'Northeast',
    state ==1 ~ 'South',
    state ==4 ~ 'South', 
    state ==9 ~ 'South',
    state == 10 ~ 'South',
    state == 17 ~ 'South',
    state == 18 ~ 'South', 
    state == 24 ~ 'South', 
    state == 33 ~ 'South', 
    state == 36 ~ 'South', 
    state == 40 ~ 'South', 
    state == 42 ~ 'South', 
    state == 43 ~ 'South',
    state == 46 ~ 'South',
    state == 13 ~'Midwest', 
    state == 14~'Midwest',
    state == 15~'Midwest',
    state == 16 ~'Midwest',
    state == 22~'Midwest',
    state == 23~'Midwest',
    state == 25~'Midwest',
    state == 27~'Midwest',
    state == 34~'Midwest',
    state == 35~'Midwest',
    state == 41~'Midwest',
    state == 49~'Midwest',
    state == 2~'West',
    state == 3~'West',
    state == 5~'West',
    state == 6~'West',
    state == 11~'West',
    state ==12~'West',
    state == 26~'West',
    state == 28~'West', 
    state == 31~'West', 
    state == 37~'West', 
    state == 44~'West',
    state == 47~'West',
    state == 50~'West'
  )))

df_usa <- df_usa %>% mutate(
  r2 = -r2,
  r3 = -r3,
  r6 = -r6,
  year_fact = as.factor(year),
  state = as.factor(state),
  r1 = as.factor(r1),
  r2 = as.factor(r2),
  r3 = as.factor(r3),
  r4 = as.factor(r4),
  r5 = as.factor(r5),
  r6 = as.factor(r6),
  s3 = as.factor(s3),
  s4 = as.factor(s4)
)

df_usa <- df_usa %>% mutate(
  president = as.factor(case_when(
    n2 <0 ~ 'Republican',
    n2>0 ~'Democrat'
  ))
)

```

```{r data expl}
sum(is.na(df_usa))
sum(df_usa$evotes)
unique(df_usa$s3)
df_usa %>% filter(s3 == -1)
df_usa %>% filter(s2==0)

#missing values 
library(naniar)
gg_miss_var(df_usa) 


#naive linear model
naive_lm <- lm(Dvote ~ ., data = df_usa)
summary(naive_lm)
#NA appear when some variables are correlated

naive_lm_2<- lm(Dvote ~ year + region + evotes + s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + r1 + r2 + r3 + r4 + r5 + r6 + n1 + n2 + n3 + n4+ president,data = df_usa) 
summary(naive_lm_2)

naive_lm_3 <- lm(Dvote ~ year + region + evotes + s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + r1 + r2 + r3 + r4 + r5 + r6 ,data = df_usa)
summary(naive_lm_3)
plot(naive_lm_3)

df_usa$s2
df_usa$s1
df_usa$r1 #0 in non southern states, but in southern states it is D-R where D=1 if the Democratic candidate for President is a Southerner and R=1 if the Republican candidate for President is a Southerner -> if 0 no difference between the candidates (whether because they are both from the south, or because not a southern state), if 1 or -1 differene between candidates
df_usa$r4
df_usa$r5
df_usa$r6

df_usa %>% filter(s3 == '-1') #quand s3 fait -1 ça veut dire que le candidat républicain est de cet état
df_usa$s5 #???
df_usa$s6 #à regarder par rapport à la variable président pour voir si croissance positive ou négative 

df_usa <- df_usa %>% mutate(
  s6_bis = case_when(
    president == 'Democrat' ~ s6,
    president == 'Republican' ~ -s6
  )
)

plot(df_usa$s6, df_usa$s6_bis) #quite a lot of changes
df_usa$s7 # if negative : for the republican ? 
df_usa$s8 #why negative values? 
df_usa$s9 #why negative values ? 

#think of a plot to represent the election outcomes 
df_usa %>% 
  group_by(year, region) %>% 
  summarise(number = n(), na_sum = sum(is.na(sum(Dvote))), s = sum(Dvote, na.rm=T)) %>% 
  mutate(number_2 = number - na_sum, avg =100*s/number_2) %>% 
  group_by(year, region) %>% 
  ggplot(aes(x = year, y=avg,fill=region)) + 
  geom_bar(stat='identity', position=position_dodge()) + 
  theme_minimal() + 
  scale_y_continuous(limits = c(0,100)) 

df_usa %>% mutate(jittime=year, state=as.factor(state)) %>%
  ggplot(mapping=aes(x=jittime,y=Dvote,col=state)) + geom_point() + stat_smooth(method="lm",level=NA,size=0.5)

```



## Linear models
```{r linear models}
library(MASS)
mod <- lm(Dvote ~. , data =df_usa)
mod_selec <- stepAIC(mod, direction = 'backward', trace = FALSE)
summary(mod_selec)
summary(mod)


panel.corrplot <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    Cor <- abs(cor(x, y)) 
    method = "color"
    txt <- paste0(prefix, format(c(Cor, 0.123456789), digits = digits)[1])
    if(missing(cex.cor)) {
        cex.cor <- 0.4 / strwidth(txt)
    }
    text(0.5, 0.5, txt,
         cex = 1 + cex.cor * Cor)
}
panel.hist <- function(x, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5))
    his <- hist(x, plot = FALSE)
    breaks <- his$breaks
    nB <- length(breaks)
    y <- his$counts
    y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = rgb(0, 1, 1, alpha = 0.5), ...)
}


# Plotting the correlation matrix : Full names did not fit so I changed the labels for the number and time on product related and administrative pages
suppressWarnings(pairs(df_usa$Dvote ~ df_usa$year + df_usa$state + df_usa$evotes + df_usa$n1 + df_usa$n2 + df_usa$n3 + df_usa$n4 + df_usa$s1 + df_usa$s2 + df_usa$s3 + df_usa$s4 + df_usa$s5 + df_usa$s6 + df_usa$s7 + df_usa$s8 + df_usa$s9,
      upper.panel = panel.corrplot,   
      lower.panel = panel.smooth, 
      diag.panel = panel.hist, na.action = na.omit))


#doesn't work
df_usa %>% ggplot(mapping=aes(y=resid(mod),col=df_usa$state[1:561]), main="s") + geom_boxplot() + labs(caption="Figure: Residuals grouped by state") + theme(plot.caption = element_text(size=18))

par(mfrow = c(2,2))
plot(df_usa$state[1:561], resid(mod)) 
plot(df_usa$year[1:561], resid(mod)) 

plot(df_usa$state[1:561], resid(mod_selec)) 
plot(df_usa$year[1:561], resid(mod_selec)) 


(df_usa %>% filter(state == '11' &  year == '1948'))$n1
plot((df_usa%>% filter(state == '2'))$year, (df_usa %>% filter(state == '11'))$n1) #we have missing data replaced by some numeric 0 values ... 

(df_usa %>% filter(state == '1' &  year == '1952'))$n1
plot((df_usa%>% filter(state == '1'))$year, (df_usa %>% filter(state == '1'))$n1)

df_usa <- df_usa %>% mutate(
  n1_bis = case_when(
    state == '11' & year == '1948' ~ 0.4561,
    state == '11' & year == '1952' ~ 0.4211,
    state == '2' & year == '1948' ~ 0.4561,
    state == '2' & year == '1952' ~ 0.4211,
    TRUE ~ n1
  )
)
#did not work... 

(df_usa %>% filter(state == '1'))$n1

plot(df_usa$state, df_usa$n1)


plot(df_usa$s7, df_usa$s8)

model_without_region <- lm(Dvote ~ year + state + s1 + s2 + s3 + s5 + s4+ s6 + r1 + r2 + r3 + r4 + r5 + r6, data = df_usa)
summary(model_without_region)
#on enlève s9 parce que c'est uniquement pour 1960 donc pas ultra utile
#on enlève n1 à n4 car ce sont des variables globales donc les mêmes pour tous les états : attention problème pour état 2 et état 11

df_usa <- df_usa %>% mutate(
  s1_bis = Dvote + s1,
  s2_bis = Dvote + s2
)

model_without_region <- lm(Dvote ~ year + state + s1_bis + s2_bis + s3 + s5 + s4+ s6 + r1 + r2 + r3 + r4 + r5 + r6, data = df_usa)
summary(model_without_region)

model_with_region <- lm(Dvote ~ year + region + s1_bis + s2_bis + s3 + s5 + s4+ s6 + r1 + r2 + r3 + r4 + r5 + r6, data = df_usa)
summary(model_with_region)

#diagnostics to plot
par(mfrow=c(1,2))
plot(model_without_region)

plot(model_without_region, which =c(1,2))
plot(model_without_region$residuals, model_without_region$fitted.values)
plot(df_usa$state[1:561], resid(model_without_region))
```


## Mixed models 
```{r mixed models, echo=FALSE}
library(lme4)
library(lmerTest)
lmer_1 <- lmer(Dvote ~ n1 + n2 + n3 + n4 + s1 + s2+ s3 + s4 + s5 + s6 + s7 + s8 + s9 + r1 + r2 + r3 + r4 + r5 + r6 + (1|year/region), data = df_usa)
Anova(lmer_1)
anova(lmer_1)
summary(lmer_1)
summary(lmer_1)

vcov(lmer_1)

plot(lmer_1)


test <- lmer(Dvote ~ n1 + n2 + n3 + n4 + (s1|year/region) + (r1|year/region), data = df_usa)
summary(test)


#fixed effects in the model : national variables since they are fixed for everyone ? or do they depend on a state in particular ? 
#variables that are correlated within year and within state : s1 to 
#only year : regional variables ? 

model_with_region <- lm(Dvote ~ year + region + s1_bis + s2_bis + s3 + s5 + s4+ s6 + r1 + r2 + r3 + r4 + r5 + r6, data = df_usa)

summary(lmer(Dvote ~  n1 + n2 + n3 + n4 + (1| year) + evotes + s1 + s2 + r3 +r4 + r5 + (1| year:region) ,data = df_usa))
#on enlève r1, r2 car correspond au South, et on enlève r6 car correspond au West donc va permettre de simplifier le modèle 
#entre parenthèse devant un | : on dit qu'on accepte que le slope varie de manière random
```

```{r map}
library(usmap)
library(ggplot2)

plot_usmap(regions = "counties") + 
  labs(title = "US Counties",
       subtitle = "This is a blank map of the counties of the United States.") + 
  theme(panel.background = element_rect(color = "black", fill = "lightblue"))


df_usa_map <- df_usa %>% 
  mutate(state = case_when(
    state == '1' ~ 'Alabama',
    state == '2' ~ 'Alaska',
    state == '3' ~ 'Arizona',
    state == '4' ~ 'Arkansas',
    state == '5' ~ 'California',
    state == '6' ~ 'Colorado',
    state == '7' ~ 'Connecticut',
    state == '8' ~ 'Delaware',
    state == '9' ~ 'Florida',
    state == '10' ~ 'Georgia',
    state == '11' ~ 'Hawaii',
    state == '12' ~ 'Idaho',
    state == '13' ~ 'Illinois',
    state == '14' ~ 'Indiana',
    state == '15' ~ 'Iowa',
    state == '16' ~ 'Kansas',
    state == '17' ~ 'Kentucky',
    state == '18' ~ 'Louisiana',
    state == '19' ~ 'Maine',
    state == '20' ~ 'Maryland',
    state == '21' ~ 'Massachusetts',
    state == '22' ~ 'Michigan',
    state == '23' ~ 'Minnesota',
    state == '24' ~ 'Mississippi',
    state == '25' ~ 'Missouri',
    state == '26' ~ 'Montana',
    state == '27' ~ 'Nebraska',
    state == '28' ~ 'Nevada',
    state == '29' ~ 'New Hampshire',
    state == '30' ~ 'New Jersey',
    state == '31' ~ 'New Mexico',
    state == '32' ~ 'New York',
    state == '33' ~ 'North Carolina',
    state == '34' ~ 'North Dakota',
    state == '35' ~ 'Ohio',
    state == '36' ~ 'Oklahoma',
    state == '37' ~ 'Oregon',
    state == '38' ~ 'Pennsylvania',
    state == '39' ~ 'Rhode Island',
    state == '40' ~ 'South Carolina',
    state == '41' ~ 'South Dakota',
    state == '42' ~ 'Tennessee',
    state == '43' ~ 'Texas',
    state == '44' ~ 'Utah',
    state == '45' ~ 'Vermont',
    state == '46' ~ 'Virginia',
    state == '47' ~ 'Washington',
    state == '48' ~ 'West Virginia',
    state == '49' ~ 'Wisconsin',
    state == '50' ~ 'Wyoming',
    TRUE ~ 'Unknown'
  ))

df_usa_map_1992 <- df_usa_map %>% filter(year == '1992')
plot_usmap(data = df_usa_map_1992, values = "Dvote", color = "red") + 
  scale_fill_continuous(
    low = "white", high = "red", name = "Vote (2015)", label = scales::comma
  ) + theme(legend.position = "right")










```

```{r}

library(plotly)
library(shiny)
library(dplyr)
#library(plotusmap)

# Assuming your data is in a data frame called "df_usa_map" with columns "year", "state", and "Dvote"

# Create a list of years
#df_usa_map <- df_usa_map %>% mutate(year = as.numeric(year))
years <- unique(df_usa_map$year)

# Define the UI for the Shiny app
ui <- fluidPage(
  titlePanel("Number of Votes by State"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("year", "Year", min = min(years), max = max(years), value = min(years), step = 4),
      hr(),
      helpText("Data from 1948 to 1992")
    ),
    mainPanel(
      plotOutput("map")
    )
  )
)

# Define the server logic for the Shiny app
server <- function(input, output) {
  output$map <- renderPlot({
    # Subset the data by the selected year
    df_subset <- filter(df_usa_map, year == input$year)
    
    # Create the map using plotusmap
    #plot_usmap(data = df_subset, values = "Dvote", color = "Dvote") +
      #labs(title = paste("Number of Votes by State in", input$year))
    
    plot_usmap(data = df_subset, values = "Dvote", color = "red") + 
  scale_fill_continuous(
    low = "white", high = "red", name = "Vote", label = scales::comma
  ) + theme(legend.position = "right")
  })
}

# Run the Shiny app
shinyApp(ui, server)



```



```{r, fig.align="center", fig.cap="Figure 1 : Democratic party candidate’s share of the vote by region between 1948 and 1992"}
df_usa %>% 
  group_by(year, region) %>% 
  summarise(number = n(), na_sum = sum(is.na(sum(Dvote))), s = sum(Dvote, na.rm=T)) %>% 
  mutate(number = number - na_sum, avg =100*s/number) %>% 
  group_by(year, region) %>% 
  ggplot(aes(x = year, y=avg,fill=region)) + 
  geom_bar(stat='identity', position=position_dodge()) + 
  theme_minimal() + 
  scale_y_continuous(limits = c(0,100)) +
  ylab("Democratic party candidate’s share of the vote")
```


